apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: myapp
        image: gcr.io/develop-459306/simple-node-amd64:blue
        ports:
        - containerPort: 8080
