apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: simple-app
        image: asia.gcr.io/develop-459306/simple-node-amd64:blue
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "staging"
        imagePullPolicy: Always

